name: First githubactions project
on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: list dir before
        run: ls -l
      - name: checkout code
        uses: actions/checkout@v2
      - name: list dir after checkout
        run: ls -l